# Generated by Django 5.0.2 on 2024-02-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.CharField(choices=[(1, 'AUTO'), (2, 'EASY'), (3, 'NORMAL'), (4, 'HARD'), (5, 'HARDER'), (6, 'INSANE'), (7, 'EASY DEMON'), (8, 'MEDIUM DEMON'), (9, 'HARD DEMON'), (10, 'INSANE DEMON'), (11, 'EXTREME DEMON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='difficulty',
            field=models.CharField(choices=[(1, 'AUTO'), (2, 'EASY'), (3, 'NORMAL'), (4, 'HARD'), (5, 'HARDER'), (6, 'INSANE'), (7, 'EASY DEMON'), (8, 'MEDIUM DEMON'), (9, 'HARD DEMON'), (10, 'INSANE DEMON'), (11, 'EXTREME DEMON')], max_length=50),
        ),
    ]
