# Generated by Django 5.0.2 on 2024-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_alter_level_difficulty_alter_review_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'AUTO'), (2, 'EASY'), (3, 'NORMAL'), (4, 'HARD'), (5, 'HARDER'), (6, 'INSANE'), (7, 'EASY DEMON'), (8, 'MEDIUM DEMON'), (9, 'HARD DEMON'), (10, 'INSANE DEMON'), (11, 'EXTREME DEMON')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'AUTO'), (2, 'EASY'), (3, 'NORMAL'), (4, 'HARD'), (5, 'HARDER'), (6, 'INSANE'), (7, 'EASY DEMON'), (8, 'MEDIUM DEMON'), (9, 'HARD DEMON'), (10, 'INSANE DEMON'), (11, 'EXTREME DEMON')]),
        ),
    ]
