# Generated by Django 4.2.10 on 2024-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_alter_level_difficulty_alter_review_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='video_url',
            field=models.URLField(default=None),
        ),
    ]
