# Generated by Django 4.2.10 on 2024-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_level_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
